#!/bin/bash
# Usage: See docker-compose.yml

set -e
set -o nounset

ARCHIVE_DESTINATION=~/Dropbox/self/Farm/
ARCHIVE_NAME=chickens-db.dump

docker compose \
  -f docker-compose.yml \
  -f docker-compose.restore.yml \
  run --rm restore
